"""add password reset token fields to users

Revision ID: 6cf1d6239a64
Revises: 9a9ef1b1f79e
Create Date: 2026-09-14 08:23:19.748658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf1d6239a64'
down_revision = '9a9ef1b1f79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token_hash')

    # ### end Alembic commands ###
