"""initial schema (pdms schema)

Revision ID: 6e017e35257d
Revises: 
Create Date: 2026-09-13 23:20:40.212953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e017e35257d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PM', 'MEMBER', name='userrole', schema='pdms'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.create_index(batch_op.f('ix_pdms_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatus', schema='pdms'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['pdms.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ON_TRACK', 'AT_RISK', 'LATE', 'COMPLETED', name='milestonestatus', schema='pdms'), nullable=False),
    sa.Column('status_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pdms.users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id'),
    schema='pdms'
    )
    op.create_table('stakeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'ACCEPTED', 'REJECTED', name='deliverystatus', schema='pdms'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('client_response_notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['pdms.users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['pdms.milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='requirementstatus', schema='pdms'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='requirementpriority', schema='pdms'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['pdms.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['pdms.users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['pdms.modules.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['pdms.stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE', name='taskstatus', schema='pdms'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['pdms.users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['pdms.milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pdms.projects.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['pdms.requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdms'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks', schema='pdms')
    op.drop_table('requirements', schema='pdms')
    op.drop_table('deliveries', schema='pdms')
    op.drop_table('stakeholders', schema='pdms')
    op.drop_table('project_members', schema='pdms')
    op.drop_table('modules', schema='pdms')
    op.drop_table('milestones', schema='pdms')
    op.drop_table('projects', schema='pdms')
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdms_users_email'))

    op.drop_table('users', schema='pdms')
    # ### end Alembic commands ###
