"""add user groups and permissions

Revision ID: 9a9ef1b1f79e
Revises: acf9b144f071
Create Date: 2026-09-14 00:45:06.563060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9ef1b1f79e'
down_revision = 'acf9b144f071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pdms'
    )
    op.create_table('group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Enum('PROJECTS', 'MODULES', 'REQUIREMENTS', 'TASKS', 'MILESTONES', 'DELIVERIES', name='resourcepage', schema='pdms'), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['pdms.groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'page', name='uq_group_permissions_group_page'),
    schema='pdms'
    )
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_group_id_groups', 'groups', ['group_id'], ['id'], referent_schema='pdms')

    # ### end Alembic commands ###

    # Seed a full-access default group and backfill existing non-admin users into it,
    # so nobody loses access the instant this migration runs (see db_updates.sql).
    op.execute("""
        INSERT INTO pdms.groups (name, description, created_at)
        VALUES ('Default Access', 'Auto-created on migration; full read/write on all pages.', now())
    """)
    op.execute("""
        INSERT INTO pdms.group_permissions (group_id, page, can_read, can_write)
        SELECT id, unnest(enum_range(NULL::pdms.resourcepage)), true, true
        FROM pdms.groups WHERE name = 'Default Access'
    """)
    op.execute("""
        UPDATE pdms.users SET group_id = (SELECT id FROM pdms.groups WHERE name = 'Default Access')
        WHERE role != 'ADMIN'
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.drop_constraint('fk_users_group_id_groups', type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('group_permissions', schema='pdms')
    op.drop_table('groups', schema='pdms')
    # ### end Alembic commands ###
