"""add is_approved to users

Revision ID: acf9b144f071
Revises: 6e017e35257d
Create Date: 2026-09-13 23:43:42.148391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf9b144f071'
down_revision = '6e017e35257d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute("UPDATE pdms.users SET is_approved = true")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='pdms') as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
